### ISSUE TITLE
Falha ao Inserir dados no arquivo

### ISSUE THREAD

**Issue by filipe0li** [Ismael66/Editor_Arquivos_Console#1]
![image](https://user-images.githubusercontent.com/76171152/144948942-b3944215-fc3d-4d55-9079-b098ef42ada1.png)
Acho melhor criar o arquivo na areá de trabalho para evitar problemas de acesso a pasta local.
E se o arquivo não existir de a opção de criar.

**Comment by Ismael66** [comment]
Problema resolvido Filipe.
Segui sua dica de resgatar o diretório do desktop.
https://github.com/Ismael66/Editor_Arquivos_Console/blob/078726303edca0613cfc9a1a6aecfd068ea6b823/Visor.cs#L11
Coloquei também um tratamento if questionando a existência do arquivo, dando a opção do usuário criar ou selecionar um arquivo.
https://github.com/Ismael66/Editor_Arquivos_Console/blob/078726303edca0613cfc9a1a6aecfd068ea6b823/Visor.cs#L91
