### ISSUE TITLE
Falta uma opção para sair do programa

### ISSUE THREAD

**Issue by filipe0li** [Ismael66/Editor_Arquivos_Console#2]
![image](https://user-images.githubusercontent.com/76171152/144949432-5b473588-4947-4b30-ab3b-3a7de0863827.png)
O programa não fornece uma opção para sair dele.

**Comment by Ismael66** [comment]
Alternativa adicionada.
https://github.com/Ismael66/Editor_Arquivos_Console/blob/1b5d823653f7d5718960ca8332130ca6ee831604/Visor.cs#L25
Ao ser escolhida faz o que foi solicitado.
https://github.com/Ismael66/Editor_Arquivos_Console/blob/1b5d823653f7d5718960ca8332130ca6ee831604/Visor.cs#L60
