### ISSUE TITLE
Os dados criados, não foram salvos no arquivo selecionado.

### ISSUE THREAD

**Issue by filipe0li** [Ismael66/Editor_Arquivos_Console#3]
![image](https://user-images.githubusercontent.com/76171152/144949963-a6c0349d-ac54-48f9-9865-7ccc9095efc1.png)
![image](https://user-images.githubusercontent.com/76171152/144950205-372c6af4-e26d-4786-a8c7-d8b5155d3631.png)

**Comment by Ismael66** [comment]
Boa tarde Filipe, problema resolvido.
Agora adiciono a informação ao arquivo logo após mostrá-la no console.
https://github.com/Ismael66/Editor_Arquivos_Console/blob/dff8bafdb3c64cd9eba03a09c288934b0288ae88/ApiViaCep/ApiViaCep.cs#L66
