### ISSUE TITLE
Mensagem sem sentido.

### ISSUE THREAD

**Issue by filipe0li** [Ismael66/Editor_Arquivos_Console#4]
![image](https://user-images.githubusercontent.com/76171152/144950294-5f5f827a-ef44-4788-911d-a91bb40f2e44.png)
A mensagem deveria ser arquivo aberto com sucesso, e pressione qualquer tecla para continuar.
Pois ao pressionar ele sai do programa

**Comment by Ismael66** [comment]
Obrigado pela dica!

![unknown](https://user-images.githubusercontent.com/85511020/145114684-d0e530c6-1954-44d2-b98a-474ffef00e90.png)
https://github.com/Ismael66/Editor_Arquivos_Console/blob/57e35cf149787beb947a97acd3e7262f8c1c07ee/Visor.cs#L124
