### ISSUE TITLE
O programa não está funcionando a opção [2] Inserir dados no arquivo

### ISSUE THREAD

**Issue by filipe0li** [Ismael66/Editor_Arquivos_Console#5]
![image](https://user-images.githubusercontent.com/76171152/144951095-5f557823-1822-4559-8fd5-45920489a61c.png)

**Comment by Ismael66** [comment]
Boa noite Filipe.
Problema resolvido.

![unknown](https://user-images.githubusercontent.com/85511020/145115703-5f741a30-2518-46ff-80a0-21b0b58ac3dd.png)
https://github.com/Ismael66/Editor_Arquivos_Console/blob/eea9348b761522fdbc8e132b8837c9285cf06a56/Visor.cs#L108
