### ISSUE TITLE
Adicionar opção para pegar todos, ou ao apertar enter já adicionar todos.

### ISSUE THREAD

**Issue by filipe0li** [Ismael66/Editor_Arquivos_Console#6]
![image](https://user-images.githubusercontent.com/76171152/144951297-bb7571d0-05a2-4b40-9156-6890d4a1d34b.png)

**Comment by Ismael66** [comment]
Obrigado pela dica Filipe.
Inseri a alternativa '0' que resgata todos os dados referentes ao Cep.

https://github.com/Ismael66/Editor_Arquivos_Console/blob/f969114843d1e7e4518679e40dc840ef243ad744/ApiViaCep/ApiViaCep.cs#L52
If que seta valor necessário ao validador, fazendo com que ele entre em todos os outros ifs.

![unknown](https://user-images.githubusercontent.com/85511020/145116620-da252f52-2a41-4332-908e-288ab9e6f0ab.png)
