### ISSUE TITLE
O código está com muita repetição

### ISSUE THREAD

**Issue by filipe0li** [Ismael66/Editor_Arquivos_Console#7]
![image](https://user-images.githubusercontent.com/76171152/145130512-499e14f0-bf19-4d61-933f-aec8fd3aaa07.png)
Ao invés de trazer o arquivo como parâmetro, retornar um stringBuilder, para diminuir o tamanho da função.

**Comment by Ismael66** [comment]
Obrigado pela dica Filipe.

![unknown](https://user-images.githubusercontent.com/85511020/145289256-637a33af-e8ef-4742-91de-4a1dd22c6f4d.png)
